version: '2'
services:
  humanresources-app:
    image: humanresources
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://humanresources-postgresql:5432/humanresources
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://humanresources-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://humanresources-elasticsearch:9200
    ports:
      - 8080:8080
  humanresources-postgresql:
    extends:
      file: postgresql.yml
      service: humanresources-postgresql
  humanresources-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: humanresources-elasticsearch
